### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'render')

### ISSUE THREAD

**Issue by jonasfroeller** [carstenlebek/svelte-email#17]
What am I doing wrong?

```bash
TypeError: Cannot read properties of undefined (reading 'render')
    at Module.render (xxx/node_modules/svelte-email/render.js:10:14)
    at POST (xxx/src/routes/subscribe-to-maillist/+server.ts:14:43)
    at Module.render_endpoint (xxx/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:24)
    at resolve (xxx/node_modules/@sveltejs/kit/src/runtime/server/respond.js:404:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.respond (xxx/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:20)
    at async file:///xxx/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22
```

```ts
export const POST = (async ({ request }) => {
    const user = await request.json();
    console.log(user);

    const email = user?.email;

    sendgrid.setApiKey(SENDGRID_API_KEY);

    const emailHtml = render({
        component: WelcomeEmail,
        props: {
            firstName: email,
        }
    });

    const options = {
        from: 'Täglich Frisches Obst - Gig-Letter <taeglichfrischesobst.noreply@gmail.com>',
        to: email,
        subject: 'Willkommen auf der Mailingliste von Täglich Frisches Obst!',
        html: emailHtml,
    };

    sendgrid.send(options);

    return new Response(JSON.stringify({ success: true }));
}) satisfies RequestHandler;
```

**Comment by jonasfroeller** [comment]
changed component to template
