### ISSUE TITLE
Broken with current Svelte versions

### ISSUE THREAD

**Issue by mikroskeem** [carstenlebek/svelte-email#2]
```
Uncaught (in promise) TypeError: template.render is not a function
    at render (render.js:6:14)
    at instance (+page.svelte:8:23)
    at init (index.mjs:2016:11)
    at new Page (+page.svelte:34:39)
    at createProxiedComponent (svelte-hooks.js?v=77ff2d76:341:9)
    at new ProxyComponent (proxy.js?v=77ff2d76:242:7)
    at new Proxy<+page> (proxy.js?v=77ff2d76:349:11)
    at construct_svelte_component_dev (index.mjs:2232:26)
    at Array.create_default_slot (root.svelte? [sm]:42:82)
    at create_slot (index.mjs:71:28)
```

https://github.com/carstenlebek/svelte-email/blob/1e43a93941bc63b21ac0a390bfceb700c6205030/src/lib/render.ts#L17-L19

<details>
<summary>Excerpt of package.json</summary>
```json
{
	"devDependencies": {
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.5.0",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"tslib": "^2.4.1",
		"typescript": "^4.9.3",
		"vite": "^4.0.0",
		"svelte-email": "^0.0.4"
	}
}
```
</details>

**Comment by ErikSandquist** [comment]
Please share some of your code. It works perfectly for me. make sure you using it in an async function with await before rendering.

An example of it:
`async function renderEmail() {
	html = await render({
		template: Receipt,
		props: {
			firstName: 'John'
		}
	});
}`

**Comment by jakedickerson** [comment]
In the README you have this as an example:

```
const emailHtml = render({
	component: Hello,
	props: {
		name: 'Svelte'
	}
});
```
But it should be this:

```
const emailHtml = render({
	template: Hello,
	props: {
		name: 'Svelte'
	}
});
```

**Comment by Antonio-Bennett** [comment]
@jakedickerson good catch. PR to update readme was merged. https://github.com/carstenlebek/svelte-email/pull/3

**Comment by s3812497** [comment]
@carstenlebek this issue can be closed

**Comment by mikroskeem** [comment]
I managed to get it working by going through new documentation - moved rendering to server side and now it works.
