### ISSUE TITLE
Error: Component.render(...) is no longer valid in Svelte 5

### ISSUE THREAD

**Issue by mmailaender** [carstenlebek/svelte-email#34]
```bash
Error: Component.render(...) is no longer valid in Svelte 5. See https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes for more information
    at Invite.render (/workspace/Test/src/lib/emails/invite.svelte:142:8)
    at Module.render (/workspace/Test/node_modules/.pnpm/svelte-email@0.0.4/node_modules/svelte-email/render.js:6:14)
    at GET (/workspace/Test/src/routes/api/auth/organization/invite/+server.ts:27:25)
    at Module.render_endpoint (/workspace/Test/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@5.0.0-next.60_vite@5.1.3/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:43:24)
    at resolve (/workspace/Test/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@5.0.0-next.60_vite@5.1.3/node_modules/@sveltejs/kit/src/runtime/server/respond.js:443:23)
    at async Module.respond (/workspace/Test/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@5.0.0-next.60_vite@5.1.3/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
    at async file:///workspace/Test/node_modules/.pnpm/@sveltejs+kit@2.5.0_@sveltejs+vite-plugin-svelte@3.0.2_svelte@5.0.0-next.60_vite@5.1.3/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22

```

Svelte Docs: https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes-server-api-changes

Problem location: https://github.com/carstenlebek/svelte-email/blob/master/src/lib/render.ts#L19

**Comment by robthepaper** [comment]
Hi there, had same issue,
don't know if it's the right way to do but here is the workaround to render in Svelte 5.

instead of this code for example :
```
import { render } from 'svelte-email'
const html = await render({
     template: template
})
```
I use this one :

```
//import { render } from 'svelte-email'
import { render } from 'svelte/server'

// === Render with props
//const rendered = await render(template, { props: { otp: '333' } })

// === Render
const rendered = await render(template)

const html = rendered?.html

```

**Comment by robthepaper** [comment]
If anyone has a good function to convert nicely to plainText...

EDIT: nevermind, just saw the import { convert } from 'html-to-text'; in the render.ts file :)

**Comment by Erim32** [comment]
Any update ?

=> https://github.com/SvelteLaunch/svelte-5-email/blob/0e3205280b5a7183834d33e6aa243d01734493e7/src/lib/render.js#L10

**Comment by valterkraemer** [comment]
My workaround based on @robthepaper's workaround, and the implementation in [`render.ts`](https://github.com/carstenlebek/svelte-email/blob/c7456ba19b464c253f0f8a13d039e11f5f4d04b8/src/lib/render.ts).

```ts
import type { Component, ComponentProps, SvelteComponent } from "svelte";
import { convert } from "html-to-text";
import { render } from "svelte/server";

const renderAsPlainText = (markup: string) => {
  return convert(markup, {
    selectors: [
      { selector: "img", format: "skip" },
      { selector: "#__svelte-email-preview", format: "skip" },
    ],
  });
};

export const renderEmail = async <
  Comp extends SvelteComponent<any> | Component<any>,
  Props extends ComponentProps<Comp> = ComponentProps<Comp>,
>(
  component: Comp,
  props?: Props,
) => {
  const rendered = render(component as any, {
    props,
  });

  const doctype =
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';

  const html = `${doctype}${rendered.body}`;

  const text = renderAsPlainText(rendered.body);

  return {
    html,
    text,
  };
};
```

Looking at the HTML output before and after looks quite similar.

**Comment by lamungu** [comment]
I can confirm with @valterkraemer's fix the package runs well on Svelte 5

@carstenlebek would it be possible to get an update on the package to allow users to use it on the new version? [I've made a fork which details the fixes provided in the thread](https://github.com/carstenlebek/svelte-email/compare/master...lamungu:svelte-email:master).

**Comment by 7haveeen** [comment]
> I can confirm with @valterkraemer's fix the package runs well on Svelte 5
> 
> @carstenlebek would it be possible to get an update on the package to allow users to use it on the new version? [I've made a fork which details the fixes provided in the thread](https://github.com/carstenlebek/svelte-email/compare/master...lamungu:svelte-email:master).

Any idea why the fix hasn't been released

**Comment by cdemi** [comment]
@carstenlebek do you think you can review and merge these changes?

**Comment by natashafenech** [comment]
@carstenlebek would it be possible to take a look at this fix?

**Comment by cdemi** [comment]
@lamungu would you consider forking this project and taking over as maintainer, since you already did the fix? It looks like this project has been abandoned; last commit is 2 years old and the maintenaer is unresponsive.

**Comment by lamungu** [comment]
@cdemi Happy to do so, I’ll work on the necessary changes needed to have a proper continuation of the project’s contribution over the next few weeks.

**Comment by mig-hub** [comment]
It does not seem to be the only thing which does not work in Svelte 5, is it? There are more warnings (which can be ignored) about creating a  `html` tag inside a webpage, but most importantly there are some wrappers that don't seem to wrap properly. Most likely because the `<slot/>` was replaced by `{@render children?.()}`.

Are there any plans to adapt this library to Svelte 5?

**Comment by cmjoseph07** [comment]
@cdemi, @natashafenech, @lamungu, @mig-hub.

Hey guys I got a fork going that has a few fixes and I want to make it a community lib now which is known as [svelty-email](https://github.com/cmjoseph07/svelty-email). Starting today I am re-writing it using Svelte 5 so if anyone wants to assist or tag along for the ride I would appreciate it.

-- This change as been added as of May 28th
